### ISSUE TITLE
Getting started tutorial issue - can't find SDL2

### ISSUE THREAD

**Issue by MattPearce** [mosra/magnum-bootstrap#8]
I just found this project and it looks great - I followed the tutorial at http://mosra.cz/blog/magnum-doc/getting-started.html and when I get to the "cmake .. -DWITH_SDL2APPLICATION=ON" step, I get the following output:

> CMake Warning at corrade/CMakeLists.txt:158 (message):
>  MSVC 2015 detected, automatically enabling MSVC2015_COMPATIBILITY.  Note
>  that some features may not be available with this compiler.
>-- Could NOT find SDL2 (missing:  SDL2_LIBRARY SDL2_INCLUDE_DIR)
>CMake Error at magnum/src/Magnum/Platform/CMakeLists.txt:163 (message):
>  SDL2 library, required by Sdl2Application, was not found.  Set
>  WITH_SDL2APPLICATION to OFF to skip building it.
>-- Configuring incomplete, errors occurred!

The guide doesn't mention where to get SDL2 from or how to include it in the project - I downloaded SDL2, but it didn't come with a CMakeLists.txt file so I'm not sure how to include it? I understand that FindSDL2.cmake is meant to find SDL2, but I'm not sure where to put it so it can find it?

**Comment by mosra** [comment]
Oh. That's a critical omission from my side, sorry! The solution is to pass location to the directory where the contents of the extracted SDL2 archive are to `CMAKE_PREFIX_PATH`, so e.g. like this:
```bat
cmake .. -DCMAKE_PREFIX_PATH="C:/Users/you/Downloads/SDL2-2.0.4" -DWITH_SDL2APPLICATION=ON
```

(Assuming that `C:/Users/you/Downloads/SDL2-2.0.4` contains `lib` and `include` folders, which are the two important things that are needed.)

Will update the docs once I get to it. Hope this helps! :)

**Comment by MattPearce** [comment]
Awesome, thanks! That was the last bit I was missing, it successfully built the project files, and the solution compiled first try :+1: Looking forward to using this engine!

**Comment by mosra** [comment]
Great to hear that! The updated docs are in mosra/magnum@dd0563300176f0faa50c0766cb97d5e376dbd802, upload will follow later.
