### ISSUE TITLE
Segment fault using Getting Started Guide on Ubuntu 16.06

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/magnum-bootstrap#9]
Attempting to get subproject compilation working leads directly to a segfault from _cmake_ of all places.

> 
> cmake .. -DWITH_SDL2APPLICATION=ON
> -- LIB_SUFFIX variable is not defined. It will be autodetected now.
> -- You can set it manually with -DLIB_SUFFIX=<value> (64 for example)
> -- LIB_SUFFIX autodetected as '', libraries will be installed into /usr/local/lib
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Found Corrade: /home/ren/Desktop/ArcAngel2D/experimenta/magnum-bootstrap/corrade/src  found components:  Containers Utility rc PluginManager 
> -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
> -- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so  
> -- Found Corrade: /home/ren/Desktop/ArcAngel2D/experimenta/magnum-bootstrap/corrade/src  found components:  Containers rc Utility PluginManager 
> -- Found Magnum: /home/ren/Desktop/ArcAngel2D/experimenta/magnum-bootstrap/magnum/src  found components:  Sdl2Application 
> Segmentation fault (core dumped)
> 

Without -SDL2_APPLICATION=ON, cmake spits out make files, but they fail to actually make (with errors related to what I assume is glfw). 

cmake --version outputs "cmake version 3.5.1", so this isn't some out of date version of cmake.

I should note I have had no real issues compiling separately (though I'd prefer to use the subproject concept to simplify my project).

**Comment by mosra** [comment]
huh.

I would need to check, the only time I saw cmake crash was when I accidentally called `add_subdirectory()` in a way that made cmake recurse infinitely. Can you post the "seemingly from glfw" errors?

**Comment by Alicemargatroid** [comment]
Sure, absolutely:

> /usr/lib/libMagnumSdl2Application.a(flextGLPlatform.cpp.o): In function `flextGLInit':
> flextGLPlatform.cpp:(.text+0x3d): undefined reference to `flextglBlitFramebufferANGLE'
> flextGLPlatform.cpp:(.text+0x5d): undefined reference to `flextglRenderbufferStorageMultisampleANGLE'
> flextGLPlatform.cpp:(.text+0x7d): undefined reference to `flextglDrawArraysInstancedANGLE'
> flextGLPlatform.cpp:(.text+0x9d): undefined reference to `flextglDrawElementsInstancedANGLE'
> flextGLPlatform.cpp:(.text+0xbd): undefined reference to `flextglVertexAttribDivisorANGLE'
> flextGLPlatform.cpp:(.text+0xdd): undefined reference to `flextglRenderbufferStorageMultisampleAPPLE'
> flextGLPlatform.cpp:(.text+0xfd): undefined reference to `flextglResolveMultisampleFramebufferAPPLE'
> flextGLPlatform.cpp:(.text+0x1bd): undefined reference to `flextglDiscardFramebufferEXT'
> flextGLPlatform.cpp:(.text+0x1dd): undefined reference to `flextglGetQueryObjecti64vEXT'
> flextGLPlatform.cpp:(.text+0x1fd): undefined reference to `flextglGetQueryObjectivEXT'
> flextGLPlatform.cpp:(.text+0x21d): undefined reference to `flextglGetQueryObjectui64vEXT'
> flextGLPlatform.cpp:(.text+0x23d): undefined reference to `flextglQueryCounterEXT'
> flextGLPlatform.cpp:(.text+0x25d): undefined reference to `flextglDrawBuffersEXT'
> flextGLPlatform.cpp:(.text+0x27d): undefined reference to `flextglBlendEquationSeparateiEXT'
> flextGLPlatform.cpp:(.text+0x29d): undefined reference to `flextglBlendEquationiEXT'
> flextGLPlatform.cpp:(.text+0x2bd): undefined reference to `flextglBlendFuncSeparateiEXT'
> flextGLPlatform.cpp:(.text+0x2dd): undefined reference to `flextglBlendFunciEXT'
> flextGLPlatform.cpp:(.text+0x2fd): undefined reference to `flextglColorMaskiEXT'
> flextGLPlatform.cpp:(.text+0x31d): undefined reference to `flextglDisableiEXT'
> flextGLPlatform.cpp:(.text+0x33d): undefined reference to `flextglEnableiEXT'
> flextGLPlatform.cpp:(.text+0x35d): undefined reference to `flextglIsEnablediEXT'
> flextGLPlatform.cpp:(.text+0x37d): undefined reference to `flextglDrawArraysInstancedEXT'
> flextGLPlatform.cpp:(.text+0x39d): undefined reference to `flextglDrawElementsInstancedEXT'
> flextGLPlatform.cpp:(.text+0x3bd): undefined reference to `flextglVertexAttribDivisorEXT'
> flextGLPlatform.cpp:(.text+0x3dd): undefined reference to `flextglFlushMappedBufferRangeEXT'
> flextGLPlatform.cpp:(.text+0x3fd): undefined reference to `flextglMapBufferRangeEXT'
> flextGLPlatform.cpp:(.text+0x41d): undefined reference to `flextglMultiDrawArraysEXT'
> flextGLPlatform.cpp:(.text+0x43d): undefined reference to `flextglMultiDrawElementsEXT'
> flextGLPlatform.cpp:(.text+0x45d): undefined reference to `flextglFramebufferTexture2DMultisampleEXT'
> flextGLPlatform.cpp:(.text+0x47d): undefined reference to `flextglRenderbufferStorageMultisampleEXT'
> flextGLPlatform.cpp:(.text+0x49d): undefined reference to `flextglBeginQueryEXT'
> flextGLPlatform.cpp:(.text+0x4bd): undefined reference to `flextglDeleteQueriesEXT'
> flextGLPlatform.cpp:(.text+0x4dd): undefined reference to `flextglEndQueryEXT'
> flextGLPlatform.cpp:(.text+0x4fd): undefined reference to `flextglGenQueriesEXT'
> flextGLPlatform.cpp:(.text+0x51d): undefined reference to `flextglGetQueryObjectuivEXT'
> flextGLPlatform.cpp:(.text+0x53d): undefined reference to `flextglGetQueryivEXT'
> flextGLPlatform.cpp:(.text+0x55d): undefined reference to `flextglIsQueryEXT'
> flextGLPlatform.cpp:(.text+0x57d): undefined reference to `flextglGetGraphicsResetStatusEXT'
> flextGLPlatform.cpp:(.text+0x59d): undefined reference to `flextglGetnUniformfvEXT'
> flextGLPlatform.cpp:(.text+0x5bd): undefined reference to `flextglGetnUniformivEXT'
> flextGLPlatform.cpp:(.text+0x5dd): undefined reference to `flextglReadnPixelsEXT'
> flextGLPlatform.cpp:(.text+0x5fd): undefined reference to `flextglActiveShaderProgramEXT'
> flextGLPlatform.cpp:(.text+0x61d): undefined reference to `flextglBindProgramPipelineEXT'
> flextGLPlatform.cpp:(.text+0x63d): undefined reference to `flextglCreateShaderProgramvEXT'
> flextGLPlatform.cpp:(.text+0x65d): undefined reference to `flextglDeleteProgramPipelinesEXT'
> flextGLPlatform.cpp:(.text+0x67d): undefined reference to `flextglGenProgramPipelinesEXT'
> flextGLPlatform.cpp:(.text+0x69d): undefined reference to `flextglGetProgramPipelineInfoLogEXT'
> flextGLPlatform.cpp:(.text+0x6bd): undefined reference to `flextglGetProgramPipelineivEXT'
> flextGLPlatform.cpp:(.text+0x6dd): undefined reference to `flextglIsProgramPipelineEXT'
> flextGLPlatform.cpp:(.text+0x6fd): undefined reference to `flextglProgramParameteriEXT'
> flextGLPlatform.cpp:(.text+0x97d): undefined reference to `flextglUseProgramStagesEXT'
> flextGLPlatform.cpp:(.text+0x99d): undefined reference to `flextglValidateProgramPipelineEXT'
> flextGLPlatform.cpp:(.text+0x9bd): undefined reference to `flextglGetSamplerParameterIivEXT'
> flextGLPlatform.cpp:(.text+0x9dd): undefined reference to `flextglGetSamplerParameterIuivEXT'
> flextGLPlatform.cpp:(.text+0x9fd): undefined reference to `flextglGetTexParameterIivEXT'
> flextGLPlatform.cpp:(.text+0xa1d): undefined reference to `flextglGetTexParameterIuivEXT'
> flextGLPlatform.cpp:(.text+0xa3d): undefined reference to `flextglSamplerParameterIivEXT'
> flextGLPlatform.cpp:(.text+0xa5d): undefined reference to `flextglSamplerParameterIuivEXT'
> flextGLPlatform.cpp:(.text+0xa7d): undefined reference to `flextglTexParameterIivEXT'
> flextGLPlatform.cpp:(.text+0xa9d): undefined reference to `flextglTexParameterIuivEXT'
> flextGLPlatform.cpp:(.text+0xabd): undefined reference to `flextglTexStorage2DEXT'
> flextGLPlatform.cpp:(.text+0xadd): undefined reference to `flextglTexStorage3DEXT'
> flextGLPlatform.cpp:(.text+0xb1d): undefined reference to `flextglDebugMessageCallbackKHR'
> flextGLPlatform.cpp:(.text+0xb3d): undefined reference to `flextglDebugMessageControlKHR'
> flextGLPlatform.cpp:(.text+0xb5d): undefined reference to `flextglDebugMessageInsertKHR'
> flextGLPlatform.cpp:(.text+0xb7d): undefined reference to `flextglGetDebugMessageLogKHR'
> flextGLPlatform.cpp:(.text+0xb9d): undefined reference to `flextglGetObjectLabelKHR'
> flextGLPlatform.cpp:(.text+0xbbd): undefined reference to `flextglGetObjectPtrLabelKHR'
> flextGLPlatform.cpp:(.text+0xbdd): undefined reference to `flextglGetPointervKHR'
> flextGLPlatform.cpp:(.text+0xbfd): undefined reference to `flextglObjectLabelKHR'
> flextGLPlatform.cpp:(.text+0xc1d): undefined reference to `flextglObjectPtrLabelKHR'
> flextGLPlatform.cpp:(.text+0xc3d): undefined reference to `flextglPopDebugGroupKHR'
> flextGLPlatform.cpp:(.text+0xc5d): undefined reference to `flextglPushDebugGroupKHR'
> flextGLPlatform.cpp:(.text+0xc7d): undefined reference to `flextglGetGraphicsResetStatusKHR'
> flextGLPlatform.cpp:(.text+0xc9d): undefined reference to `flextglGetnUniformfvKHR'
> flextGLPlatform.cpp:(.text+0xcbd): undefined reference to `flextglGetnUniformivKHR'
> flextGLPlatform.cpp:(.text+0xcdd): undefined reference to `flextglGetnUniformuivKHR'
> flextGLPlatform.cpp:(.text+0xcfd): undefined reference to `flextglReadnPixelsKHR'
> flextGLPlatform.cpp:(.text+0xd1d): undefined reference to `flextglDrawBuffersNV'
> flextGLPlatform.cpp:(.text+0xd3d): undefined reference to `flextglDrawArraysInstancedNV'
> flextGLPlatform.cpp:(.text+0xd5d): undefined reference to `flextglDrawElementsInstancedNV'
> flextGLPlatform.cpp:(.text+0xd7d): undefined reference to `flextglBlitFramebufferNV'
> flextGLPlatform.cpp:(.text+0xd9d): undefined reference to `flextglRenderbufferStorageMultisampleNV'
> flextGLPlatform.cpp:(.text+0xdbd): undefined reference to `flextglVertexAttribDivisorNV'
> flextGLPlatform.cpp:(.text+0xddd): undefined reference to `flextglPolygonModeNV'
> flextGLPlatform.cpp:(.text+0xdfd): undefined reference to `flextglReadBufferNV'
> flextGLPlatform.cpp:(.text+0xe1d): undefined reference to `flextglGetBufferPointervOES'
> flextGLPlatform.cpp:(.text+0xe3d): undefined reference to `flextglMapBufferOES'
> flextGLPlatform.cpp:(.text+0xe5d): undefined reference to `flextglUnmapBufferOES'
> flextGLPlatform.cpp:(.text+0xe7d): undefined reference to `flextglCompressedTexImage3DOES'
> flextGLPlatform.cpp:(.text+0xe9d): undefined reference to `flextglCompressedTexSubImage3DOES'
> flextGLPlatform.cpp:(.text+0xebd): undefined reference to `flextglCopyTexSubImage3DOES'
> flextGLPlatform.cpp:(.text+0xedd): undefined reference to `flextglFramebufferTexture3DOES'
> flextGLPlatform.cpp:(.text+0xefd): undefined reference to `flextglTexImage3DOES'
> flextGLPlatform.cpp:(.text+0xf1d): undefined reference to `flextglTexSubImage3DOES'
> flextGLPlatform.cpp:(.text+0xf3d): undefined reference to `flextglBindVertexArrayOES'
> flextGLPlatform.cpp:(.text+0xf5d): undefined reference to `flextglDeleteVertexArraysOES'
> flextGLPlatform.cpp:(.text+0xf7d): undefined reference to `flextglGenVertexArraysOES'
> flextGLPlatform.cpp:(.text+0xf9d): undefined reference to `flextglIsVertexArrayOES'
>

**Comment by mosra** [comment]
Sorry for the very late reply -- I tried on my side with base project from `magnum-bootstrap` with latest corrade and magnum added via `add_subdirectory()` but couldn't reproduce either of the problems you have -- with `WITH_SDL2APPLICATION=ON` it just found everything and running `make` was then successfull, without it CMake rightfully complained that `find_package(Magnum REQUIRED Sdl2Application)` couldn't found the `Sdl2Application` component.

The problem you are describing could be caused by some unfortunate combination of outdated `FindMagnum.cmake`/`FindCorrade.cmake`/`FindSDL2.cmake` modules in either of the projects.

**Comment by renindustries** [comment]
@mosra 

It looks as if that is the case, as updating has fixed these problems. Thank you!

**Comment by Alicemargatroid** [comment]
@mosra Problem resolved, must have been a transient issue.
